# build front-end
FROM node:lts-alpine AS frontend

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN npm install npm -g

WORKDIR /app

COPY ./package.json /app

COPY ./pnpm-lock.yaml /app

RUN yarn config set registry 'https://registry.npmmirror.com/'

RUN yarn config delete proxy

RUN npm config set registry 'https://registry.npmmirror.com'

RUN npm install

COPY . /app

RUN npm run build

# build backend
FROM node:lts-alpine as backend

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN yarn config set registry 'https://registry.npmmirror.com/'

RUN yarn config delete proxy

RUN npm config set registry 'https://registry.npmmirror.com'

RUN npm install npm -g

WORKDIR /app

COPY /service/package.json /app

COPY /service/npm-lock.yaml /app

RUN npm install

COPY /service /app

RUN npm build

# service
FROM node:lts-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN yarn config set registry 'https://registry.npmmirror.com/'

RUN yarn config delete proxy

RUN npm config set registry 'https://registry.npmmirror.com'

RUN npm install npm -g

WORKDIR /app

COPY /service/package.json /app

COPY /service/npm-lock.yaml /app

RUN npm install --production && rm -rf /root/.npm /root/.npm-store /usr/local/share/.cache /tmp/*

COPY /service /app

COPY --from=frontend /app/dist /app/public

COPY --from=backend /app/build /app/build

EXPOSE 3002

CMD ["npm", "run", "prod"]
